# Generated by Django 3.0.3 on 2020-08-05 14:49

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TradeDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='net_profit',
            field=djmoney.models.fields.MoneyField(decimal_places=5, default_currency='USD', editable=False, max_digits=100),
        ),
        migrations.AlterUniqueTogether(
            name='stockdetail',
            unique_together={('stock_name', 'date_sold'), ('stock_name', 'date_purchased')},
        ),
    ]
