# Generated by Django 3.0.3 on 2020-08-05 15:59

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TradeDetails', '0004_auto_20200805_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='ending_price',
            field=djmoney.models.fields.MoneyField(decimal_places=3, default_currency='USD', max_digits=25),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='net_profit',
            field=djmoney.models.fields.MoneyField(decimal_places=3, default_currency='USD', max_digits=100),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='starting_price',
            field=djmoney.models.fields.MoneyField(decimal_places=3, default_currency='USD', max_digits=20),
        ),
    ]
