# Generated by Django 3.0.3 on 2020-08-06 14:47

from django.db import migrations, models
import transfers.models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptransfer',
            name='date_fulfilled',
            field=models.DateField(help_text='YYYY-MM-DD', validators=[transfers.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='apptransfer',
            name='date_initiated',
            field=models.DateField(help_text='YYYY-MM-DD', validators=[transfers.models.validate_date]),
        ),
    ]
