# Generated by Django 3.0.3 on 2020-07-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='user',
        ),
    ]
